### ISSUE TITLE
Server doesn't start on heroku dyno

### ISSUE THREAD

**Issue by hadokee** [rs/pushd#100]
I'm trying to deploy server on heroku but it crashes with this error:

> 2015-02-06T15:48:27.123442+00:00 heroku[web.1]: Starting process with command `coffee pushd.coffee`
> 2015-02-06T15:48:29.886746+00:00 app[web.1]:   at Object.<anonymous> (/app/pushd.coffee:7:12)
> 2015-02-06T15:48:29.886747+00:00 app[web.1]:   at Object.<anonymous> (/app/pushd.coffee:1:1)
> 2015-02-06T15:48:29.886722+00:00 app[web.1]: Error: Cannot find module './settings'
> 2015-02-06T15:48:29.886740+00:00 app[web.1]:   at Function.Module._resolveFilename (module.js:338:15)
> 2015-02-06T15:48:29.886742+00:00 app[web.1]:   at Function.Module._load (module.js:280:25)
> 2015-02-06T15:48:29.886743+00:00 app[web.1]:   at Module.require (module.js:364:17)
> 2015-02-06T15:48:29.886750+00:00 app[web.1]: 
> 2015-02-06T15:48:29.886748+00:00 app[web.1]:   at Module._compile (module.js:456:26)
> 2015-02-06T15:48:29.886745+00:00 app[web.1]:   at require (module.js:380:17)
> 2015-02-06T15:48:30.717472+00:00 heroku[web.1]: Process exited with status 1
> 2015-02-06T15:48:30.728983+00:00 heroku[web.1]: State changed from starting to crashed

I created the Procfile with this content:
> web: coffee pushd.coffee

EDIT: I solved by remove settings.coffee from .gitignore

**Comment by hadokee** [comment]
A new error:

> 2015-02-06T16:24:15.022800+00:00 heroku[web.1]: Starting process with command `coffee pushd.coffee`
> 2015-02-06T16:24:18.071125+00:00 app[web.1]: info: Registering push service: apns
> 2015-02-06T16:24:18.077312+00:00 app[web.1]: info: Registering push service: http
> 2015-02-06T16:24:18.077805+00:00 app[web.1]: info: Registering push service: mpns-raw
> 2015-02-06T16:24:18.271524+00:00 app[web.1]:               ^
> 2015-02-06T16:24:18.077683+00:00 app[web.1]: info: Registering push service: mpns-tile
> 2015-02-06T16:24:18.270884+00:00 app[web.1]: 
> 2015-02-06T16:24:18.271297+00:00 app[web.1]:         throw er; // Unhandled 'error' event
> 2015-02-06T16:24:18.267124+00:00 app[web.1]: info: Listening on tcp port 15712
> 2015-02-06T16:24:18.271017+00:00 app[web.1]: events.js:72
> 2015-02-06T16:24:18.070089+00:00 app[web.1]: info: Registering push service: event-source
> 2015-02-06T16:24:18.077053+00:00 app[web.1]: info: Registering push service: gcm
> 2015-02-06T16:24:18.077471+00:00 app[web.1]: info: Registering push service: mpns-toast
> 2015-02-06T16:24:18.268022+00:00 app[web.1]: info: Listening on udp port 80
> 2015-02-06T16:24:18.273375+00:00 app[web.1]: Error: bind EACCES
> 2015-02-06T16:24:18.273378+00:00 app[web.1]:   at errnoException (dgram.js:458:11)
> 2015-02-06T16:24:18.273379+00:00 app[web.1]:   at dgram.js:211:28
> 2015-02-06T16:24:18.273381+00:00 app[web.1]:   at dns.js:72:18
> 2015-02-06T16:24:18.273383+00:00 app[web.1]:   at process._tickCallback (node.js:442:13)
> 2015-02-06T16:24:18.273387+00:00 app[web.1]:   at node.js:929:3
> 2015-02-06T16:24:18.273384+00:00 app[web.1]:   at Function.Module.runMain (module.js:499:11)
> 2015-02-06T16:24:18.273386+00:00 app[web.1]:   at startup (node.js:119:16)
> 2015-02-06T16:24:18.273389+00:00 app[web.1]: 
> 2015-02-06T16:24:19.007795+00:00 heroku[web.1]: Process exited with status 8
> 2015-02-06T16:24:19.022440+00:00 heroku[web.1]: State changed from starting to crashed

I tried to do this in settings.coffee:

`tcp_port: process.env.PORT || 3000`
