### ISSUE TITLE
Netmask Problem when Posting and Event

### ISSUE THREAD

**Issue by geisi93** [rs/pushd#112]
Hi,

I try to post an event:

http://localhost:8001/event/Test

but I always get this netmask error:

Error: Invalid net address: ::1<br> &nbsp;at new Netmask (C:\Users\geisrieglm\pushd\node_modules\netmask\lib\netmask.js:69:15)<br> &nbsp;at Netmask.contains (C:\Users\geisrieglm\pushd\node_modules\netmask\lib\netmask.js:83:14)<b

Does anybody know what the problem is and how to fix it? Thanks

**Comment by geisi93** [comment]
I managed it by commenting some parts of the settings out: 

exports.server =
    redis_port: 6379
    redis_host: 'localhost'
    #redis_socket: '/var/run/redis/redis.sock'
    #redis_auth: 'password'
    tcp_port: 8001
    udp_port: 8001
    access_log: yes
#    acl:
        # restrict publish access to private networks
#        publish: ['127.0.0.1', '10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']
#    auth:
#        # require HTTP basic authentication, username is 'admin' and
#        # password is 'password'
#        #
#        # HTTP basic authentication overrides IP-based authentication
#        # if both acl and auth are defined.
#       admin:
#            password: 'password'
#            realms: ['register', 'publish']

**Comment by bajalovic** [comment]
I also get this error, and it is also fixed if I comment out acl, but that is not good. 

Is there any other solution how to fix this?

**Comment by akkina9** [comment]
I am facing the same issue..

**Comment by akkina9** [comment]
the following workaround did the trick for me: https://github.com/rs/pushd/pull/122
