### ISSUE TITLE
File Logs are not working

### ISSUE THREAD

**Issue by tmnuwan12** [rs/pushd#124]
I have following log config in settings.coffee.

exports['logging'] = [
        transport: 'File'
        options:
            level: 'silly'
			prettyPrint: true
			fileName: '/users/nthusitha/log/pushd.log'
			
    ]

But I get following error when I try to start the pushd.

Error: Cannot log to file without filename or stream.
  at new exports.File (/Users/nthusitha/Desktop/pushd/pushd/node_modules/winston/lib/winston/transports/file.js:65:11)
  at [object Object].Logger.add (/Users/nthusitha/Desktop/pushd/pushd/node_modules/winston/lib/winston/logger.js:430:41)
  at Object.winston.(anonymous function) [as add] (/Users/nthusitha/Desktop/pushd/pushd/node_modules/winston/lib/winston.js:85:34)
  at Object.<anonymous> (/Users/nthusitha/Desktop/pushd/pushd/pushd.coffee:25:20)
  at Object.<anonymous> (/Users/nthusitha/Desktop/pushd/pushd/pushd.coffee:1:1)
  at Module._compile (module.js:460:26)

**Comment by tmnuwan12** [comment]
I managed to get his fixed by using (View > Show invisible Character) TextMate. Seems like my indentation of the settings is wrong. The editor mixed up the tabs and space characters. After viewing invisible characters I managed to remove all tab characters and replaced them with space characters. It's working for me now. Hope this helps.
Thanks
