### ISSUE TITLE
Problems while intsaling

### ISSUE THREAD

**Issue by Senseju5** [rs/pushd#159]
Hey guys, 
could you tell me with what versions of linux, redis, nodejs, npm and coffee script you tested this service and it worked?
Cause I was trying to install it in 
Linux srmwlinuxdev1 2.6.32-696.10.2.el6.x86_64 #1 SMP Tue Sep 12 14:33:29 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
with such versions of above mentioned tools
 node -v
v8.4.0
 npm -v
5.3.0
redis-server -v
Redis server v=3.2.10 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=f83a0de63af68303
coffee -v
CoffeeScript version 1.8.0

and cloning from git runs normaly, but whenever i try to get all the dependencies and run: 
npm install 
I get lots of errors as it is not able to build hiredis node module with node-gyp rebuild command.

**Comment by mmontone** [comment]
I'm able to build with node version 0.10.0, but with lots of warnings, and when I try to run I get this:

```
/opt/pushd/node_modules/node-gcm/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (/usr/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/pushd/node_modules/node-gcm/node_modules/request/node_modules/hawk/lib/index.js:5:33)
```

To me pushd looks outdated, doesn't use newer versions of dependencies and node ecosystem changes too fast.

**Comment by mmontone** [comment]
Btw, this fork installed fine for me: https://github.com/Binarypark/pushd.git

Example Dockerfile:
```
FROM debian:jessie-slim

# Install system dependencies.
RUN \
  apt-get update && \
  #apt-get -y upgrade && \
  apt-get install -y \
  build-essential software-properties-common \
  git zip curl

RUN curl --silent --location https://deb.nodesource.com/setup_4.x | bash - \
    && apt-get install -y nodejs

# Install application dependencies.
RUN npm install coffee-script -g

RUN git clone https://github.com/Binarypark/pushd.git /opt/pushd/
RUN cd /opt/pushd/ && npm install
ADD ./main.sh /usr/local/bin/main.sh
ADD ./settings.coffee /opt/pushd/settings.coffee

EXPOSE 80

CMD ["/usr/local/bin/main.sh"]
```
