### ISSUE TITLE
Unable to install pushd on windows machine

### ISSUE THREAD

**Issue by Nagamohan1** [rs/pushd#97]
Hi,

I am new to pushd, i try to install pushd using gitbash command line console.

Installed the prerequisites Node.js,Redis, npm

i am getting following error when i run "npm install", please help me in resolving the issue.

$ npm install
-
> hiredis@0.1.17 install c:\Git-projects\pushd\node_modules\hiredis
> node-gyp rebuild

c:\Git-projects\pushd\node_modules\hiredis>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
c:\Git-projects\pushd\node_modules\hiredis\build\deps\hiredis.vcxproj(18,3): error MSB4019: The imported project "c:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `c:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Git-projects\pushd\node_modules\hiredis
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! hiredis@0.1.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.1.17 install script.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Git-projects\pushd
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by tylkomat** [comment]
I encountered the same problems and use a virtual machine for pushd. Additionally I use samba to share the source so I can develop using my windows tools.

**Comment by geisi93** [comment]
I had the same trouble on a windows machine, I had to install Python and to add it to my path. I had to force the installation afterwards, but it worked ;)
